operation: |
    mutation {
        u1: createUser(data: {id: "u1", email: "u1@example.com", name: "U1"}) {
            id @bind(name: "u1id")
        }
        u2: createUser(data: {id: "u2", email: "u2@example.com", name: "U2"}) {
            id @bind(name: "u2id")
        }
        u3: createUser(data: {id: "u3", email: "u3@example.com", name: "U3"}) {
            id @bind(name: "u3id")
        }
        u4: createUser(data: {id: "u4", email: "u4@example.com", name: "U4"}) {
            id @bind(name: "u4id")
        }
    }
auth: |
    {
        "role": "admin"
    }
