stages:
  - operation: |
      mutation {
        createChat(data: {id: "u1-u2", title: "Hey u2 (by u1)!", participations: [{user: {id: "u1"}}, {user: {id: "u2"}}]}) {
          id
          title
          owner {
            id
          }
          participations @unordered {
            user {
              id
            }
          }
        }
      }
    auth: |
      {
          "sub": "u1"
      }
    response: |
      {
        "data": {
          "createChat": {
            "id": "u1-u2",
            "title": "Hey u2 (by u1)!",
            "owner": {
              "id": "u1"
            },
            "participations": [
              {
                "user": {
                  "id": "u1"
                }
              },
              {
                "user": {
                  "id": "u2"
                }
              }
            ]
          }
        }
      }

  - operation: |
      mutation {
        createChat(data: {id: "u2-u3", title: "Hey u3 (by u2)!", participations: [{user: {id: "u2"}}, {user: {id: "u3"}}]}) {
          id
          title
          owner {
            id
          }
          participations @unordered {
            user {
              id
            }
          }
        }
      }
    auth: |
      {
          "sub": "u2"
      }
    response: |
      {
        "data": {
          "createChat": {
            "id": "u2-u3",
            "title": "Hey u3 (by u2)!",
            "owner": {
              "id": "u2"
            },
            "participations": [
              {
                "user": {
                  "id": "u2"
                }
              },
              {
                "user": {
                  "id": "u3"
                }
              }
            ]
          }
        }
      }

  - operation: |
      mutation {
        createChat(data: {id: "u1-u3", title: "Hey u3 (by u1)!", participations: [{user: {id: "u1"}}, {user: {id: "u3"}}]}) {
          id
          title
        }
      }
    auth: |
      {
          "sub": "u1"
      }
    response: |
      {
        "data": {
          "createChat": {
            "id": "u1-u3",
            "title": "Hey u3 (by u1)!"
          }
        }
      }
